# Generated by Django 2.0.1 on 2018-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juegosmundial', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejemplo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname2', models.CharField(max_length=10)),
                ('lastname2', models.CharField(max_length=10)),
                ('ejemplos', models.ManyToManyField(to='juegosmundial.ejemplo')),
            ],
        ),
    ]
