# Generated by Django 2.0.1 on 2018-01-29 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegosmundial', '0002_ejemplo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ejemxejem2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ejem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegosmundial.ejemplo')),
            ],
        ),
        migrations.RemoveField(
            model_name='ejemplo2',
            name='ejemplos',
        ),
        migrations.AddField(
            model_name='ejemxejem2',
            name='ejem2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegosmundial.ejemplo2'),
        ),
    ]
