# Generated by Django 2.0.1 on 2018-01-29 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('juegosmundial', '0003_auto_20180129_0604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descpregunta', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='PrexRes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_val', models.BooleanField(default=False)),
                ('idpregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegosmundial.Pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrespuesta', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='ejemxejem2',
            name='ejem',
        ),
        migrations.RemoveField(
            model_name='ejemxejem2',
            name='ejem2',
        ),
        migrations.DeleteModel(
            name='ejemplo',
        ),
        migrations.DeleteModel(
            name='ejemplo2',
        ),
        migrations.DeleteModel(
            name='ejemxejem2',
        ),
        migrations.AddField(
            model_name='prexres',
            name='idrespuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='juegosmundial.Respuesta'),
        ),
    ]
